# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\rmetatrader.v1\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x15\n\x13GetLastErrorRequest\";\n\x14GetLastErrorResponse\x12#\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x14.metatrader.v1.Error\"\x07\n\x05\x45mpty\"\x8e\x01\n\x0e\x43onnectRequest\x12\x11\n\x04path\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05login\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x15\n\x08password\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06server\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x07\n\x05_pathB\x08\n\x06_loginB\x0b\n\t_passwordB\t\n\x07_server\"0\n\nTimeFilter\x12\x11\n\tdate_from\x18\x01 \x01(\x03\x12\x0f\n\x07\x64\x61te_to\x18\x02 \x01(\x03*\xfa\x01\n\x0f\x45NUM_ORDER_TYPE\x12\x12\n\x0eORDER_TYPE_BUY\x10\x00\x12\x13\n\x0fORDER_TYPE_SELL\x10\x01\x12\x18\n\x14ORDER_TYPE_BUY_LIMIT\x10\x02\x12\x19\n\x15ORDER_TYPE_SELL_LIMIT\x10\x03\x12\x17\n\x13ORDER_TYPE_BUY_STOP\x10\x04\x12\x18\n\x14ORDER_TYPE_SELL_STOP\x10\x05\x12\x1d\n\x19ORDER_TYPE_BUY_STOP_LIMIT\x10\x06\x12\x1e\n\x1aORDER_TYPE_SELL_STOP_LIMIT\x10\x07\x12\x17\n\x13ORDER_TYPE_CLOSE_BY\x10\x08\x32\x9e\x01\n\x11MetaTraderService\x12>\n\x07\x43onnect\x12\x1d.metatrader.v1.ConnectRequest\x1a\x14.metatrader.v1.Error\x12I\n\x0cGetLastError\x12\x14.metatrader.v1.Empty\x1a#.metatrader.v1.GetLastErrorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENUM_ORDER_TYPE']._serialized_start=360
  _globals['_ENUM_ORDER_TYPE']._serialized_end=610
  _globals['_ERROR']._serialized_start=31
  _globals['_ERROR']._serialized_end=69
  _globals['_GETLASTERRORREQUEST']._serialized_start=71
  _globals['_GETLASTERRORREQUEST']._serialized_end=92
  _globals['_GETLASTERRORRESPONSE']._serialized_start=94
  _globals['_GETLASTERRORRESPONSE']._serialized_end=153
  _globals['_EMPTY']._serialized_start=155
  _globals['_EMPTY']._serialized_end=162
  _globals['_CONNECTREQUEST']._serialized_start=165
  _globals['_CONNECTREQUEST']._serialized_end=307
  _globals['_TIMEFILTER']._serialized_start=309
  _globals['_TIMEFILTER']._serialized_end=357
  _globals['_METATRADERSERVICE']._serialized_start=613
  _globals['_METATRADERSERVICE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
