# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_calc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order_calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10order_calc.proto\x12\rmetatrader.v1\x1a\x0c\x63ommon.proto\"w\n\x16OrderCalcMarginRequest\x12.\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1e.metatrader.v1.ENUM_ORDER_TYPE\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\r\n\x05price\x18\x04 \x01(\x01\"N\n\x17OrderCalcMarginResponse\x12\x0e\n\x06margin\x18\x01 \x01(\x01\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.metatrader.v1.Error\"\x91\x01\n\x16OrderCalcProfitRequest\x12.\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1e.metatrader.v1.ENUM_ORDER_TYPE\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x12\n\nprice_open\x18\x04 \x01(\x01\x12\x13\n\x0bprice_close\x18\x05 \x01(\x01\"N\n\x17OrderCalcProfitResponse\x12\x0e\n\x06profit\x18\x01 \x01(\x01\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.metatrader.v1.Error2\xcc\x01\n\x10OrderCalcService\x12[\n\nCalcMargin\x12%.metatrader.v1.OrderCalcMarginRequest\x1a&.metatrader.v1.OrderCalcMarginResponse\x12[\n\nCalcProfit\x12%.metatrader.v1.OrderCalcProfitRequest\x1a&.metatrader.v1.OrderCalcProfitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERCALCMARGINREQUEST']._serialized_start=49
  _globals['_ORDERCALCMARGINREQUEST']._serialized_end=168
  _globals['_ORDERCALCMARGINRESPONSE']._serialized_start=170
  _globals['_ORDERCALCMARGINRESPONSE']._serialized_end=248
  _globals['_ORDERCALCPROFITREQUEST']._serialized_start=251
  _globals['_ORDERCALCPROFITREQUEST']._serialized_end=396
  _globals['_ORDERCALCPROFITRESPONSE']._serialized_start=398
  _globals['_ORDERCALCPROFITRESPONSE']._serialized_end=476
  _globals['_ORDERCALCSERVICE']._serialized_start=479
  _globals['_ORDERCALCSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
