# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trade_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trade_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12trade_events.proto\x12\rmetatrader.v1\x1a\x0c\x63ommon.proto\"\x85\x01\n!SubscribeTradeTransactionsRequest\x12\x1a\n\rfrom_time_msc\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x1d\n\x10poll_interval_ms\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x10\n\x0e_from_time_mscB\x13\n\x11_poll_interval_ms\"\xfd\x01\n\x15TradeTransactionEvent\x12\x13\n\x0b\x64\x65\x61l_ticket\x18\x01 \x01(\x04\x12\x14\n\x0corder_ticket\x18\x02 \x01(\x04\x12\x17\n\x0fposition_ticket\x18\x03 \x01(\x04\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x0e\n\x06volume\x18\x05 \x01(\x01\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x0e\n\x06profit\x18\x07 \x01(\x01\x12\x10\n\x08time_msc\x18\x08 \x01(\x03\x12\x0c\n\x04type\x18\t \x01(\x05\x12\r\n\x05\x65ntry\x18\n \x01(\x05\x12(\n\x05\x65rror\x18\x0b \x01(\x0b\x32\x14.metatrader.v1.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error2\x8c\x01\n\x12TradeEventsService\x12v\n\x1aSubscribeTradeTransactions\x12\x30.metatrader.v1.SubscribeTradeTransactionsRequest\x1a$.metatrader.v1.TradeTransactionEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBETRADETRANSACTIONSREQUEST']._serialized_start=52
  _globals['_SUBSCRIBETRADETRANSACTIONSREQUEST']._serialized_end=185
  _globals['_TRADETRANSACTIONEVENT']._serialized_start=188
  _globals['_TRADETRANSACTIONEVENT']._serialized_end=441
  _globals['_TRADEEVENTSSERVICE']._serialized_start=444
  _globals['_TRADEEVENTSSERVICE']._serialized_end=584
# @@protoc_insertion_point(module_scope)
