# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trade_events_pb2 as trade__events__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trade_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeEventsServiceStub(object):
    """Trade transaction event streaming.

    This is the FIRST streaming RPC in the contract. It is a strictly additive,
    backward-compatible addition: no existing service, message, field, or field
    number is modified. All existing RPCs remain unary and unchanged.

    The MetaTrader 5 Python API exposes no push/event callback (OnTradeTransaction
    exists only in MQL5/EA), so events are emulated by server-side polling of the
    historical deals feed (history_deals_get) over an advancing time window. A
    "trade transaction" is a newly added deal (the Python-observable equivalent of
    MQL5 OnTradeTransaction DEAL_ADD).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeTradeTransactions = channel.unary_stream(
                '/metatrader.v1.TradeEventsService/SubscribeTradeTransactions',
                request_serializer=trade__events__pb2.SubscribeTradeTransactionsRequest.SerializeToString,
                response_deserializer=trade__events__pb2.TradeTransactionEvent.FromString,
                _registered_method=True)


class TradeEventsServiceServicer(object):
    """Trade transaction event streaming.

    This is the FIRST streaming RPC in the contract. It is a strictly additive,
    backward-compatible addition: no existing service, message, field, or field
    number is modified. All existing RPCs remain unary and unchanged.

    The MetaTrader 5 Python API exposes no push/event callback (OnTradeTransaction
    exists only in MQL5/EA), so events are emulated by server-side polling of the
    historical deals feed (history_deals_get) over an advancing time window. A
    "trade transaction" is a newly added deal (the Python-observable equivalent of
    MQL5 OnTradeTransaction DEAL_ADD).
    """

    def SubscribeTradeTransactions(self, request, context):
        """Open a long-lived subscription that streams one TradeTransactionEvent per
        newly added deal on the connected account as it is observed.

        Delivery is exactly-once per subscription, in chronological order, with no
        duplicates (de-duplicated on deal ticket, so same-millisecond deals are both
        delivered). Idle streams stay open via transport-level keepalive
        (gRPC/HTTP-2 PING); no application-level heartbeat events are emitted.
        The stream ends on client cancellation/disconnect or on a terminal failure
        (signalled by a final event carrying `error`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeEventsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeTradeTransactions': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTradeTransactions,
                    request_deserializer=trade__events__pb2.SubscribeTradeTransactionsRequest.FromString,
                    response_serializer=trade__events__pb2.TradeTransactionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metatrader.v1.TradeEventsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metatrader.v1.TradeEventsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeEventsService(object):
    """Trade transaction event streaming.

    This is the FIRST streaming RPC in the contract. It is a strictly additive,
    backward-compatible addition: no existing service, message, field, or field
    number is modified. All existing RPCs remain unary and unchanged.

    The MetaTrader 5 Python API exposes no push/event callback (OnTradeTransaction
    exists only in MQL5/EA), so events are emulated by server-side polling of the
    historical deals feed (history_deals_get) over an advancing time window. A
    "trade transaction" is a newly added deal (the Python-observable equivalent of
    MQL5 OnTradeTransaction DEAL_ADD).
    """

    @staticmethod
    def SubscribeTradeTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metatrader.v1.TradeEventsService/SubscribeTradeTransactions',
            trade__events__pb2.SubscribeTradeTransactionsRequest.SerializeToString,
            trade__events__pb2.TradeTransactionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
